name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_PATH: RabbitMQ
  PACKAGE: Alex75.Utils.RabbitMQ
  VERSION: "0.1.{$GITHUB_RUN_NUMBER}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal  --filter "TestCategory!=SKIP_ON_DEPLOY

    - name: Pack
      run: |
        echo #dotnet pack -c Release --no-restore --include-symbols -p:PackageVersion=$VERSION
        echo version=$VERSION.$GITHUB_RUN_ID
        dotnet pack -c Release --no-restore --include-symbols $PROJECT_PATH/*.*proj -p:PackageVersion=$VERSION
    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: nupkg
    #    path: ${{} env.}
