name: .NET Core

# example: https://github.com/giraffe-fsharp/Giraffe/blob/master/.github/workflows/build.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #release:
  #  types:
  #    - published

env:
  PROJECT_FOLDER: RabbitMQ
  VERSION: "0.1.${{github.run_number}}"  # $GITHUB_RUN_NUMBER can't be use here'
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal  --filter "TestCategory!=SKIP_ON_DEPLOY

    - name: Pack
      run: |
        echo Build package Version=$VERSION
        dotnet pack -c Release --no-build --include-symbols $PROJECT_FOLDER/*.*proj -p:PackageVersion=$VERSION -o nupkgs
    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: nupkg
    #    path: ./nupkgs/*.nupkg
    #    if-no-files-found: error

    - name: Publish to NuGet
      run: |
        echo Publish package Version $VERSION
        dotnet nuget push ./nupkgs/*.nupkg  --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
        
      


